config/routes.rb
Rails.application.routes.draw do

  resources :docs do
    member do
       get :download
    end
  end
    
  resources :searches
  resources :contacts do
    member do
       get :verify
       get :check
    end
    collection do
      get :check_all
      get :list
      get :photo
      get :print
      get :print_photo
    end        
  end
  resources :albums

  match "/signin" => "services#signin", via: :get
  match "/signout" => "services#signout", via: :get

  match '/auth/:service/callback' => 'services#create', via: :all
  match '/auth/failure' => 'services#failure', via: :all

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  devise_for :users, :controllers => { :sessions => "user_sessions" },
                     :path_names => { :sign_in => 'login', 
                                      :sign_out => 'logout',  
                                      :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password
       get :collect_photos_to_album 
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       get :style 
       put :update_avatar
       put :star
    end
  end

  resources :hits
  resources :urls, :as => :referrer_urls, :controller => :referrer_urls

  resources :comments

  resources :photos do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :critiques do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :questions do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :answers do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :articles do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :reviews do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :testimonies do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :echos do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end
  
  resources :prayer_requests do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :prayers do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end
  
  resources :announcements
  resources :dashboard
  
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings', via: :get
    
    resources :announcements
    resources :commits
    match '/users/search' => 'users#search', via: :get
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end

  match 'cc', :controller => :contacts, :action => :index, via: :get
  root        :controller => configatron.main_content.pluralize, :action => :index
  match ':action', :controller => 'pages', via: :get
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  include Content
  belongs_to        :user
  has_attached_file :file
  
  def before_save
    if !self.name or self.name.length < 1
      self.name = self.file_file_name
    end
  end
  
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_filter :logged_in?, :except => [:index, :show]
  # GET /docs
  # GET /docs.xml
  def index
    @docs = Doc.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @docs }
    end
  end

  # GET /docs/1
  # GET /docs/1.xml
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @doc }
    end
  end

  def download
    @doc = Doc.find(params[:id])
    send_file @doc.file.path
  end
  
  # GET /docs/new
  # GET /docs/new.xml
  def new
    @doc = Doc.new(:user_id => current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @doc }
    end
  end

  # GET /docs/1/edit
  def edit
    @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.xml
  def create
    @doc = Doc.new(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to(@doc, :notice => 'Doc was successfully created.') }
        format.xml  { render :xml => @doc, :status => :created, :location => @doc }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.xml
  def update
    @doc = Doc.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to(@doc, :notice => 'Doc was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @doc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.xml
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to(docs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/_form.html.erb
<%= form_for @doc, :url => docs_path, :html => { :multipart => true } do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

  <%= f.file_field 'file', :style=>"width: 600px" %><br><br>

  <% if @doc.id %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<h1>Documents </h1>

<table class="sortable">

<% @docs.each do |doc| %>
  <tr>
    <td><%= link_to doc.name, doc.file.url %></td>
    <td><% if doc.user_id %> <%= doc.user_id %> <%end%></td>
    <td width="20px"></td>
    <td><%= link_to "Download", download_doc_path(doc) %></td>
    <td width="20px"></td>
    <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
    <td width="20px"></td>
    <td><%= link_to 'Delete', doc, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Doc', new_doc_path %>

app/views/docs/new.html.erb
<h1>Upload file</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= link_to @doc.name, @doc.file.url %>
</p>

<p>
  <%= link_to "download", download_doc_path(@doc) %>
</p>

<% if @doc.user_id %>
<p>
  By <%= @doc.user.name %>
</p>
<% end %>


<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>