config/routes.rb
Rails.application.routes.draw do

  resources :docs do
    member do
       get :download
    end
  end
    
  resources :searches
  resources :contacts do
    member do
       get :verify
       get :check
    end
    collection do
      get :check_all
      get :list
      get :photo
      get :print
      get :print_photo
    end        
  end
  resources :albums

  match "/signin" => "services#signin", via: :get
  match "/signout" => "services#signout", via: :get

  match '/auth/:service/callback' => 'services#create', via: :all
  match '/auth/failure' => 'services#failure', via: :all

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  devise_for :users, :controllers => { :sessions => "user_sessions" },
                     :path_names => { :sign_in => 'login', 
                                      :sign_out => 'logout',  
                                      :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password
       get :collect_photos_to_album 
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       get :style 
       put :update_avatar
       put :star
    end
  end

  resources :hits
  resources :urls, :as => :referrer_urls, :controller => :referrer_urls

  resources :comments

  resources :photos do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :critiques do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :questions do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :answers do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :articles do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :reviews do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :testimonies do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :echos do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end
  
  resources :prayer_requests do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :prayers do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end
  
  resources :announcements
  resources :dashboard
  
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings', via: :get
    
    resources :announcements
    resources :commits
    match '/users/search' => 'users#search', via: :get
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end

  match 'cc', :controller => :contacts, :action => :index, via: :get
  root        :controller => configatron.main_content.pluralize, :action => :index
  match ':action', :controller => 'pages', via: :get
end

app/views/shared/_announcements.html.erb
<div id="announcement" class="container">
    <%- for announcement in announcements_for_display -%>
      	<h1><%=h announcement.headline -%></h1>
		<p><%=h announcement.message -%></p>
    <%- end -%>
</div>

app/views/shared/_global_links.html.erb
<% if logged_in? %>
 	<strong><%= current_user.login %></strong> | 
	<%= link_to "Dashboard", root_url %> | 
	<%= link_to "My Account", profile_url(current_user) %> | 
	<% if admin? -%><%= link_to "Administration", admin_root_url %> | <% end -%>
	<%= link_to "Log out", destroy_user_session_path %>
<% else %>
	<%= link_to "Sign up", new_user_registration_path %> | 
	<%= link_to "Log in", new_user_session_path %>
<% end %>

app/views/shared/_google_analytics.html.erb
<% if Rails.env.production? %>
  <script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-24495109-1']);
	_gaq.push(['_trackPageview']);

	(function() {
	  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
  </script>
<% end %>

app/views/shared/_google_plus1.html.erb
<!-- Place this tag where you want the +1 button to render -->
<g:plusone size="medium" annotation="none" href="<%=url%>"></g:plusone>

app/views/shared/_in_place_notice.html.erb
<div id = "<%= notice_id %>" 
     class="error-notification supernovabg" 
     onclick="$(this).hide()"
     style="display: none;">
</div>

app/views/shared/_new_button.html.erb
<% post_path = "/" + @current_content.pluralize + "/new" %>
<% notice_id = "post_#{@current_content}_notice" %>

<%= render :partial => 'shared/in_place_notice', :locals => {:notice_id=> notice_id} %>		

<% if current_user == nil %>
    <%= link_to  "Post new", "#", 
    :onClick => "show_flash_login('#{notice_id}', 'post',  '#{post_path}' )", 
    :class => (@adding_post ? "youarehere" : ""),     
    :title => "Post a new #{@current_content.humanize.downcase}" %>
<% else %>
    <%= link_to "Post new", post_path,  
    :id=>"nav-askquestion", 
    :class => (@adding_post ? "youarehere" : ""),     
    :title => "Post a new #{@current_content.humanize.downcase}" %>
<% end %>  

app/views/shared/_tab.html.erb
<%= link_to tab,
            {:controller => @current_content.pluralize.to_sym, :tab   => tab,  :page  => 1},
            {:class => (@tab == tab ? "youarehere" : ""), :title => title} %>

app/views/shared/_tabs.html.erb
<div id="tabs">
  <%if false%>
    <a href="?tab=interesting" class="youarehere" title="Posts that may be of interest to you based on your history and tag preferences">interesting</a>
    <%= render :partial=>'shared/tab', :locals => {:tab => "hot", :title => "Post with most active over the last few days"} %>
    <%= render :partial=>'shared/tab', :locals=>{:tab=>"hot",  :title=>"photos with the most votes over the last few days"} %>
    <%= render :partial=>'shared/tab', :locals=>{:tab=>"week", :title=>"photos with the most votes this week"} %>
    <%= render :partial=>'shared/tab', :locals=>{:tab=>"month",:title=>"photos with the most votes this month"} %>
    <%= render :partial=>'shared/tab', :locals=>{:tab=>"ever", :title=>"photos with the most votes ever"} %>
  <%end%>
    <%= render :partial=>'/shared/new_button' %>
    <%= render :partial=>'/shared/tab', :locals=>{:tab=>"recent", :title=>"recent #{@current_content.pluralize.humanize.downcase}"} %>
    <%= render :partial=>'/shared/tab', :locals=>{:tab=>"popular", :title=>"top voted #{@current_content.pluralize.humanize.downcase}"} %>
  <% if logged_in? %>
    <%= render :partial=>'/shared/tab', :locals=>{:tab=>"my",  :title=>"my own #{@current_content.pluralize.humanize.downcase}"} %>
    <%= render :partial=>'/shared/tab', :locals=>{:tab=>"favorite", :title=>"my favorites #{@current_content.pluralize.humanize.downcase}"} %>
  <%end%>    
 </div>