config/routes.rb
Rails.application.routes.draw do

  resources :docs do
    member do
       get :download
    end
  end
    
  resources :searches
  resources :contacts do
    member do
       get :verify
       get :check
    end
    collection do
      get :check_all
      get :list
      get :photo
      get :print
      get :print_photo
    end        
  end
  resources :albums

  match "/signin" => "services#signin", via: :get
  match "/signout" => "services#signout", via: :get

  match '/auth/:service/callback' => 'services#create', via: :all
  match '/auth/failure' => 'services#failure', via: :all

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  devise_for :users, :controllers => { :sessions => "user_sessions" },
                     :path_names => { :sign_in => 'login', 
                                      :sign_out => 'logout',  
                                      :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password
       get :collect_photos_to_album 
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       get :style 
       put :update_avatar
       put :star
    end
  end

  resources :hits
  resources :urls, :as => :referrer_urls, :controller => :referrer_urls

  resources :comments

  resources :photos do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :critiques do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :questions do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :answers do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :articles do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :reviews do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :testimonies do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :echos do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end
  
  resources :prayer_requests do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end

  resources :prayers do
     member do
       put :vote_up
       put :vote_down
       put :star
       put :comment
    end
  end
  
  resources :announcements
  resources :dashboard
  
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings', via: :get
    
    resources :announcements
    resources :commits
    match '/users/search' => 'users#search', via: :get
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end

  match 'cc', :controller => :contacts, :action => :index, via: :get
  root        :controller => configatron.main_content.pluralize, :action => :index
  match ':action', :controller => 'pages', via: :get
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validate :label, :uniqueness => true, :presence => true
  validates_uniqueness_of :identifier
  
  # Story any kind of object in the value field.
  # This is nice, but you should also make it editable through admin/settings
  serialize :value
  
  def self.load(identifier)
    identifier = identifier.to_s if identifier.is_a?(Symbol)
    
    find_by_identifier(identifier)
  end
  
  # Return the value for a setting
  def self.get(identifier)
    identifier = identifier.to_s if identifier.is_a?(Symbol)
    
    begin
      setting = find_by_identifier(identifier)
    rescue
      setting = nil
    end
    
    setting.nil? ? "" : setting.value
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController  
  def index
    @settings = Setting.all
  end
  
  def update
    params[:settings].each do |input|
      setting = Setting.find(input[0])
=begin      
      value = case(setting.field_type)
      when 'string':        input[1].to_s
      when 'integer':       input[1].to_i
      when 'boolean':       input[1].to_s
      when 'float':         input[1].to_f
      end
      
      setting.update_attribute(:value, value)
=end
    end
    
    flash[:notice] = "Settings have been saved."
    
    redirect_to :action => :index
  end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
  def settings_field(setting)
    render :partial => "#{setting.field_type}", :locals => {:setting => setting}
  end
end

app/views/admin/settings/_boolean.html.erb
<div class="setting textfield" id="setting=<%= setting.id %>">
	<p>
		<strong><%= setting.label %></strong><br />
		<small><%= setting.description %></small>
	</p>
	<p>
		<%= select_tag("settings[#{setting.id}]", options_for_select([["On", 1], ["Off", 0]], :selected => setting.value) ) %>
	</p>
</div>

app/views/admin/settings/_float.html.erb
<div class="setting textfield" id="setting=<%= setting.id %>">
	<p>
		<strong><%= setting.label %></strong><br />
		<small><%= setting.description %></small>
	</p>
	<p>
		<%= text_field_tag("settings[#{setting.id}]", setting.value.to_s, :size => 40 ) %>
	</p>
</div>

app/views/admin/settings/_integer.html.erb
<div class="setting textfield" id="setting=<%= setting.id %>">
	<p>
		<strong><%= setting.label %></strong><br />
		<small><%= setting.description %></small>
	</p>
	<p>
		<%= text_field_tag("settings[#{setting.id}]", setting.value.to_s, :size => 40 ) %>
	</p>
</div>

app/views/admin/settings/_string.html.erb
<div class="setting textfield" id="setting=<%= setting.id %>">
	<p>
		<strong><%= setting.label %></strong><br />
		<small><%= setting.description %></small>
	</p>
	<p>
		<%= text_field_tag("settings[#{setting.id}]", setting.value.to_s, :size => 40 ) %>
	</p>
</div>

app/views/admin/settings/index.html.erb
<% content_for :header do -%>
Application Settings
<% end -%>

<% content_for :sidebar do -%>
<p>
	These are site-wide settings. They will be used through-out your application.
</p>
<p>
	To add new settings, simple create a new row in the 'settings' table. 
</p>
<% end -%>

<h3>General</h3>

<pre>	
	rails c 
	Setting.create!(:label =>"Flight Mode", :identifier => "flight",
	 :description => "Turn ruby flight mode on or off", :field_type =>"integer", :value =>"1")
</pre>
<p>
Boolean, Float, String or Integer are valid field types, default is string
</p>
<% if !@settings.blank?%>
<%= form_for @settings,:url => admin_settings_update_settings_path do |f| %>

<% for setting in @settings %>  
	<%= fields_for "setting[]", setting do |f| %>  
		<%= settings_field(Setting.load(setting.identifier)) %>
		<% end %>  
<% end %>

<div id="submitbutton">
	<p><%= submit_tag 'Save Settings' %></p>
	
</div> 
<% end %>
<% else %>
<h3>Currently, there are no settings present, add one with the above code!</h3>

<% end %>